# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: Ant@1
  displayName: 'FULL sandbox validation'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['IsDestructive'],'False'))
  inputs:
      workingDirectory: SFDC-MAIN
      buildFile: 'SFDC-MAIN/build.xml'
      options: -Dloginurl=$(loginurl) -Dworkspace=$(workspace) -Dpassword=$(borg-koneInterface-full-pwd) -Dusername=$(borg-koneInterface-full-user) -DjarWorkspace=$(jarWorkspace) validate
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
