# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: Ant@1
  displayName: 'sandbox validation'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['IsDestructive'],'False'))
  inputs:
      workingDirectory: "LWCDemo"
      buildFile: 'LWCDemo/build.xml'
      options: -Dloginurl=https://venkyvenkatesh-dev-ed.my.salesforce.com -Dworkspace=$(workspace) -Dpassword=Abhi@2025 -Dusername=venkatesh@abc.com -DjarWorkspace=$(jarWorkspace) validate
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
